name: Mise à jour Classements (Tous)

on:
  schedule:
    - cron: '0 8 * * *' # Tous les jours à 8h00 UTC (9h ou 10h en France)
  workflow_dispatch: # Bouton manuel

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les librairies
        run: |
          pip install requests beautifulsoup4 pandas lxml html5lib

      # --- C'EST ICI QUE TU LANCES TES 4 SCRIPTS ---
      - name: Lancer les scripts de scraping
        run: |
          python scripts/maj_classement_d2.py
          python scripts/maj_classement_d3.py
          python scripts/maj_classement_d4.py

      # --- SAUVEGARDE DE TOUS LES FICHIERS JSON ---
      - name: Sauvegarder et Envoyer les changements
        run: |
          git config --global user.name "Bot Classement"
          git config --global user.email "bot@asesg.fr"
          
          # On ajoute TOUS les json du dossier data
          git add assets/data/*.json
          
          # On valide (le "|| echo" évite que ça plante s'il n'y a rien de nouveau)
          git commit -m "Mise à jour automatique des classements" || echo "Pas de changement"
          git push