name: Mise à jour Classement

on:
  schedule:
    - cron: '0 8 * * *' # Lance le script tous les jours à 8h00 UTC
  workflow_dispatch: # Permet de le lancer manuellement si besoin

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v3

      - name: Installer Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Installer les librairies
        run: |
          pip install requests beautifulsoup4 pandas lxml html5lib

      - name: Lancer le script de scraping
        run: python scripts/maj_classement_d2.py

      - name: Sauvegarder et Envoyer les changements
        run: |
          git config --global user.name "Bot Classement"
          git config --global user.email "bot@asesg.fr"
          git add assets/data/classement_d2.json
          git commit -m "Mise à jour automatique du classement D2" || echo "Pas de changement"
          git push